export const db = "main-stackoverflow"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentCollection = "comments"
export const voteCollection = "Votes"
export const  questionAttechementBucket = "question-attachement"